# Generated by Django 3.2 on 2025-05-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=255, unique=True)),
                ('game_mode', models.CharField(choices=[('online', 'Online'), ('bot', 'Bot')], default='online', max_length=10)),
                ('player_1_fingerprint', models.CharField(max_length=255)),
                ('player_2_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_1_ip', models.GenericIPAddressField()),
                ('player_2_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('player_1_country', models.CharField(max_length=100)),
                ('player_1_city', models.CharField(max_length=100)),
                ('player_2_country', models.CharField(blank=True, max_length=100, null=True)),
                ('player_2_city', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_cooperation_percent', models.FloatField(default=0)),
                ('player_1_cooperation_percent', models.FloatField(default=0)),
                ('player_2_cooperation_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('player_1_action', models.CharField(max_length=10)),
                ('player_2_action', models.CharField(blank=True, max_length=10, null=True)),
                ('round_start_time', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='the_game.gamematch')),
            ],
        ),
    ]
