# Generated by Django 3.2 on 2025-05-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='completed_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='round_end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='round_start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
