# Generated by Django 3.2.25 on 2025-06-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameround',
            name='avg_cooperation_percent',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_1_cooperation_percent',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_1_cumulative_score',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_2_cooperation_percent',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='player_2_cumulative_score',
        ),
    ]
