# Generated by Django 3.2.25 on 2025-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='avg_cooperation_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_1_cooperation_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_1_cumulative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_2_cooperation_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_2_cumulative_score',
            field=models.IntegerField(default=0),
        ),
    ]
