# Generated by Django 3.2 on 2025-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='player_1_action',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
