# Generated by Django 3.2 on 2025-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0002_alter_gameround_player_1_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='player_1_final_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='player_2_final_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='round_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
