<<<<<<< HEAD
# Generated by Django 3.2.25 on 2025-06-02 14:26

from django.db import migrations, models
=======
# Generated by Django 3.2 on 2025-05-27 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid
>>>>>>> youssef


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UltimatumGameRound',
            fields=[
                ('row_number', models.AutoField(primary_key=True, serialize=False)),
                ('game_match_uuid', models.CharField(db_index=True, max_length=8)),
                ('round_number', models.IntegerField()),
                ('player_1_fingerprint', models.CharField(max_length=255)),
                ('player_2_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_1_country', models.CharField(default='Unknown', max_length=100)),
                ('player_1_city', models.CharField(default='Unknown', max_length=100)),
                ('player_2_country', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('player_2_city', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('game_mode', models.CharField(choices=[('online', 'Online'), ('bot', 'Bot')], default='online', max_length=10)),
                ('player_1_role', models.CharField(blank=True, choices=[('proposer', 'Proposer'), ('responder', 'Responder')], max_length=10, null=True)),
                ('player_2_role', models.CharField(blank=True, choices=[('proposer', 'Proposer'), ('responder', 'Responder')], max_length=10, null=True)),
                ('proposer_offer', models.IntegerField(blank=True, null=True)),
                ('proposer_keeps', models.IntegerField(blank=True, null=True)),
                ('responder_response', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True)),
                ('player_1_coins_made_in_round', models.IntegerField(default=0)),
                ('player_2_coins_made_in_round', models.IntegerField(default=0)),
                ('players_sum_coins_in_round', models.IntegerField(default=0)),
                ('round_player_1_cumulative_score', models.IntegerField(default=0)),
                ('round_player_2_cumulative_score', models.IntegerField(default=0)),
                ('players_sum_coins_total', models.IntegerField(default=0)),
                ('player_1_final_score', models.IntegerField(default=0)),
                ('player_2_final_score', models.IntegerField(default=0)),
                ('round_acceptance_rate', models.FloatField(default=0)),
                ('match_acceptance_rate', models.FloatField(default=0)),
                ('round_average_offer', models.FloatField(default=0)),
                ('match_average_offer', models.FloatField(default=0)),
                ('round_start', models.CharField(blank=True, max_length=50, null=True)),
                ('round_end', models.CharField(blank=True, max_length=50, null=True)),
                ('match_completed_at', models.CharField(blank=True, max_length=50, null=True)),
                ('match_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['game_match_uuid', 'round_number'],
                'unique_together': {('game_match_uuid', 'round_number')},
            },
=======
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('bot', 'Bot')], max_length=8)),
                ('proposer_id', models.CharField(max_length=64)),
                ('responder_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('accepted', models.BooleanField(null=True)),
                ('sent_by', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='ultimatum.match')),
            ],
>>>>>>> youssef
        ),
    ]
