# Generated by Django 3.2.25 on 2025-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UltimatumGameRound',
            fields=[
                ('row_number', models.AutoField(primary_key=True, serialize=False)),
                ('game_match_uuid', models.CharField(db_index=True, max_length=8)),
                ('round_number', models.IntegerField()),
                ('player_1_fingerprint', models.CharField(max_length=255)),
                ('player_2_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('player_1_country', models.CharField(default='Unknown', max_length=100)),
                ('player_1_city', models.CharField(default='Unknown', max_length=100)),
                ('player_2_country', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('player_2_city', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('game_mode', models.CharField(choices=[('online', 'Online'), ('bot', 'Bot')], default='online', max_length=10)),
                ('player_1_offer', models.IntegerField(blank=True, null=True)),
                ('player_2_offer', models.IntegerField(blank=True, null=True)),
                ('player_1_response_to_p2_offer', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True)),
                ('player_2_response_to_p1_offer', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True)),
                ('player_1_coins_made_in_round', models.IntegerField(default=0)),
                ('player_2_coins_made_in_round', models.IntegerField(default=0)),
                ('players_sum_coins_in_round', models.IntegerField(default=0)),
                ('round_player_1_cumulative_score', models.IntegerField(default=0)),
                ('round_player_2_cumulative_score', models.IntegerField(default=0)),
                ('players_sum_coins_total', models.IntegerField(default=0)),
                ('player_1_final_score', models.IntegerField(default=0)),
                ('player_2_final_score', models.IntegerField(default=0)),
                ('round_acceptance_rate', models.FloatField(default=0)),
                ('match_acceptance_rate', models.FloatField(default=0)),
                ('round_average_offer', models.FloatField(default=0)),
                ('match_average_offer', models.FloatField(default=0)),
                ('round_start', models.CharField(blank=True, max_length=50, null=True)),
                ('round_end', models.CharField(blank=True, max_length=50, null=True)),
                ('match_completed_at', models.CharField(blank=True, max_length=50, null=True)),
                ('match_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['game_match_uuid', 'round_number'],
                'unique_together': {('game_match_uuid', 'round_number')},
            },
        ),
    ]
